### ISSUE TITLE
Does not match background color scheme

### ISSUE THREAD

**Issue by aahnik** [pawamoy/mkdocs-coverage#4]
![cov-back](https://user-images.githubusercontent.com/66209958/118609971-ebb10d00-b7d8-11eb-8894-d2b6034a822b.gif)

How can I make it match the background theme?

**Comment by pawamoy** [comment]
Yeah the coverage report currently follows your system preferences *at generation time*. I don't think it's possible to switch the theme of the coverage HTML report while browsing it. Maybe @nedbat or @vsalvino could confirm that?

**Comment by nedbat** [comment]
The choice of light/dark is dynamic based on your OS or browser settings.  Try this page: https://nedbatchelder.com/files/sample_coverage_html/index.html.  When I change my Mac OS mode, the page changes.   Perhaps something about the iframing is getting in the way?

**Comment by pawamoy** [comment]
OK, I was completely wrong then (fortunately!) :sweat_smile: 
I guess the issue comes from the iframe indeed. I'll investigate, thanks @nedbat!

**Comment by nedbat** [comment]
Let me know if there's something I can change in the HTML to make it work better.

**Comment by vsalvino** [comment]
What you are describing is how iframes work (embedding one HTML file inside another).

If you would like the content of the iframe to match the parent page, you will have to not use an iframe but instead inject the HTML contents directly into the parent page (using server side rendering or javascript), and then provide your own CSS to style it accordingly.

There may also be some circumstances where the parent page can use CSS to target the elements within the iframe to customize the design. It may be worth a try for your use-case.

**Comment by pawamoy** [comment]
Is it even possible to toggle the coverage report theme (between light and dark) without changing the browser/system preference?
It seems there's only one `style.css` file that uses `@media (prefers-color-scheme: dark)` to change some properties when the preference is set to dark.

**Comment by vsalvino** [comment]
Correct, it is not possible to toggle it without changing browser/system preference. This could of course be refactored to use javascript to set a CSS class based on browser/system preference or a toggle button.

However you can override the styles with plain CSS if needed.

**Comment by my1e5** [comment]
Interested to know if there are any further updates on this

**Comment by pawamoy** [comment]
No comments = no updates. Happy to review PRs if you want to contribute a fix :slightly_smiling_face:

**Comment by my1e5** [comment]
I'm not sure what changed - but I noticed today that my coverage report is automatically changing its color scheme.

<img src="https://github.com/user-attachments/assets/1f06522d-e81f-4d16-9591-b2ebc22c2ba1" width=70% height=70%>

```
  "mkdocs-material==9.5.39",
  "mkdocs-coverage==1.1.0",
```

**Comment by pawamoy** [comment]
Might be an update in the HTML generated by coveragepy itself :slightly_smiling_face: I'll try this too and close if this is fixed! Thanks for the update!

**Comment by pawamoy** [comment]
Yay that works! Amazing :smile:
